[package]
name = "test-bitcoincore-rpc"
description = "Test Dogecoin Core RPC server"
version = "0.0.1"
edition = "2021"
license = "CC0-1.0"
<<<<<<< HEAD
homepage = "https://github.com/apezord/ord-dogecoin"
repository = "https://github.com/apezord/ord-dogecoin"
=======
homepage = "https://github.com/ordinals/ord"
repository = "https://github.com/ordinals/ord"
>>>>>>> 5c09dd6c38136a95370eb5274d23a38b59306bb8

[dependencies]
bitcoin = { version = "0.30.0", features = ["serde", "rand"] }
hex = "0.4.3"
jsonrpc-core = "18.0.0"
jsonrpc-derive = "18.0.0"
jsonrpc-http-server = "18.0.0"
ord-bitcoincore-rpc = "0.17.0"
reqwest = { version = "0.11.10", features = ["blocking"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = { version = "1.0.81" }
